# Generated by Django 2.0.7 on 2018-07-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drg_defintion', models.CharField(max_length=255)),
                ('provider_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.BigIntegerField()),
                ('hospital_referral', models.CharField(max_length=255)),
                ('total_discharges', models.IntegerField()),
                ('avg_cov_charges', models.FloatField()),
                ('avg_total_payments', models.FloatField()),
                ('avg_medicare_payments', models.FloatField()),
            ],
        ),
    ]
