# Generated by Django 2.0.7 on 2018-07-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180703_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='total_discharges',
            field=models.BigIntegerField(),
        ),
    ]
