# Generated by Django 2.0.7 on 2018-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180703_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='avg_cov_charges',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='avg_medicare_payments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='avg_total_payments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_discharges',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zipcode',
            field=models.CharField(max_length=255),
        ),
    ]
