# Generated by Django 2.0.7 on 2018-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180703_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='avg_cov_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='avg_medicare_payments',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='avg_total_payments',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_discharges',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zipcode',
            field=models.BigIntegerField(),
        ),
    ]
